## numpy array creation example with array() and print the properties

In [3]:
import numpy as np

In [5]:
def function():
    l1 = [10,20,30,40,50]
    print(11)
    print(f"Type = {type(11)}")
    print(f"l1[0] = {type(l1[0])}")

function()    

11
Type = <class 'int'>
l1[0] = <class 'int'>


In [7]:
def function2():
    n_arr =np.array([11,22,33,44,55])
    print(n_arr)
    print(f"Type = {type(n_arr)}")

function2()                    
                    

[11 22 33 44 55]
Type = <class 'numpy.ndarray'>


In [9]:
def function3():
    n_arr =np.array([10,20,30,40,50,60])
    print(n_arr)
    print(f"Type = {type(n_arr)}")
    print(f"DType = {n_arr.dtype}")
    print(f"Item size = {n_arr.itemsize}")
    print(f"size = {n_arr.size}")
    print(f"nbytes = {n_arr.nbytes}")
    print(f"dim = {n_arr.ndim}")
function3()
    

[10 20 30 40 50 60]
Type = <class 'numpy.ndarray'>
DType = int64
Item size = 8
size = 6
nbytes = 48
dim = 1


In [10]:
def printProperties(arr):
    print(arr)
    print(f"Type = {type(arr)}")
    print(f"DType = {arr.dtype}")
    print(f"Item size = {arr.itemsize}")
    print(f"Size = {arr.size}")
    print(f"NDIM = {arr.ndim}")
    print(f"NBYTES = {arr.nbytes}")

n1 = np.array([2,5,8,9,3,4])
printProperties(n1)


[2 5 8 9 3 4]
Type = <class 'numpy.ndarray'>
DType = int64
Item size = 8
Size = 6
NDIM = 1
NBYTES = 48


In [12]:
n3 = np.array([11,22,33,44],dtype = np.int32)
printProperties(n3)


[11 22 33 44]
Type = <class 'numpy.ndarray'>
DType = int32
Item size = 4
Size = 4
NDIM = 1
NBYTES = 16


In [13]:
n4= np.array([1.15,2.31,3.8])
printProperties(n4)

[1.15 2.31 3.8 ]
Type = <class 'numpy.ndarray'>
DType = float64
Item size = 8
Size = 3
NDIM = 1
NBYTES = 24


In [14]:
n5= np.array(["C","C++","Java","Python"])
printProperties(n5)

['C' 'C++' 'Java' 'Python']
Type = <class 'numpy.ndarray'>
DType = <U6
Item size = 24
Size = 4
NDIM = 1
NBYTES = 96


In [15]:
country=np.array(["India","USA","Australia"])
printProperties(country)

['India' 'USA' 'Australia']
Type = <class 'numpy.ndarray'>
DType = <U9
Item size = 36
Size = 3
NDIM = 1
NBYTES = 108


In [16]:
n1 = np.array([11,22,33,44,55,66,77,88])
print(n1)

[11 22 33 44 55 66 77 88]


In [17]:
print(n1[2])  

33


In [20]:
print(len(n1))  

8


In [21]:
print(n1[4]) 

55


In [22]:
print(n1[-1]) 

88


In [23]:
print(n1[-8]) 

11


In [24]:
print(n1[2:5]) 

[33 44 55]


In [25]:
print(f"NDIM ={n1.ndim}" )

NDIM =1


In [26]:
print(f"Shape = {n1.shape}")

Shape = (8,)


In [27]:
n1= n1.reshape([4,2])
print(n1)

[[11 22]
 [33 44]
 [55 66]
 [77 88]]


In [28]:
print(f"NDIM ={n1.ndim}" )

NDIM =2


In [29]:
print(f"Shape = {n1.shape}")

Shape = (4, 2)


arr1=np.arange(0,10)
print(arr1)

In [30]:
arr1=np.arange(10,25,2)
print(arr1)


[10 12 14 16 18 20 22 24]


In [31]:
arr2=np.zeros(5)
print(arr2)

[0. 0. 0. 0. 0.]


In [32]:
arr2=np.ones(5)
print(arr2)

[1. 1. 1. 1. 1.]


In [33]:
n1=np.array([11,22,33,44])
n2=np.array([10,20,30,40])
print(f"N1 = {n1}")
print(f"N2 = {n2}")
print(n1+n2)

N1 = [11 22 33 44]
N2 = [10 20 30 40]
[21 42 63 84]


In [34]:
n1=np.random.random(5)      # generate any random 5 floating-point numbers 
print(n1)

[0.18028964 0.63867585 0.83729713 0.13141261 0.50660474]


In [35]:
n4=np.random.randint(1,10,4)       # any four integer numbers are randomly generated between 1 to 10       
print(n4) 

[2 8 3 9]


In [36]:
 # broadcast operation

n1=np.array([11,22,33,44]) 

print(n1*5)
print(n1 + 10) 
print(n1 -10)

[ 55 110 165 220]
[21 32 43 54]
[ 1 12 23 34]


In [37]:
# slicing-Boolean indexing
n1=np.array([10,20,30,40,50])  
print(f"n1[[false,false,true,true,false]]={n1[[False,False,True,True,False]]}")

n1[[false,false,true,true,false]]=[30 40]


In [38]:
# filtering
salaries = np.array([10000, 15000, 12000, 30000, 45000, 50000, 55000, 
120000, 150000]) 
print(salaries[salaries > 100000])


[120000 150000]
